/****** Script for SelectTopNRows command from SSMS  ******/
SELECT 
      PERSACTHST.ACTION_CODE
      ,PERSACTHST.EFFECT_DATE
      ,PERSACTHST.ACTION_NBR
      ,PERSACTHST.EMPLOYEE
	  ,EMPLOYEE.FIRST_NAME
	  ,EMPLOYEE.LAST_NAME
      ,PERSACTHST.REASON_01
      ,PERSACTHST.DATE_STAMP
      ,PERSACTHST.ACTION_TYPE
  FROM PERSACTHST
  left join EMPLOYEE on EMPLOYEE.EMPLOYEE = PERSACTHST.EMPLOYEE
  order by EMPLOYEE.EMPLOYEE